kind: ConfigMap
apiVersion: v1
metadata:
  namespace: clients
  name: java-producer-config
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.properties: |-
     bootstrap.servers=pkc-0zxpp.europe-west2.gcp.confluent.cloud:9092
     ssl.endpoint.identification.algorithm=https
     security.protocol=SASL_SSL
     sasl.mechanism=PLAIN
     sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='FVVHSUT4KPVTHGCL' password='cvYwQoFfrBAsbf8ycAn8q/uHHi+1DrZ6SIxt5xQCBvXA2ohx26Yuo25dt3LGaBiL';
     client.id=chuck-java-producer
     key.serializer=org.apache.kafka.common.serialization.StringSerializer
     value.serializer=org.apache.kafka.common.serialization.StringSerializer
     topic=chuck-java-topic
