---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-consumer
  name: java-consumer
  namespace: clients
  annotations:
    configmap.reloader.stakater.com/reload: "java-consumer-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-consumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-consumer
    spec:
      containers:
      - name: java-consumer
        image: ogomezso/java-cloud-consumer:0.0.1
        resources: {}
        volumeMounts:
        - name: app-config-volume
          mountPath: /config
      volumes:
        - name: app-config-volume
          configMap:
            name: java-consumer-config
