---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-producer
  name: java-producer
  namespace: clients
  annotations:
    configmap.reloader.stakater.com/reload: "java-producer-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-producer
    spec:
      containers:
      - name: java-producer
        image: ogomezso/java-cloud-producer:0.0.2
        resources: {}
        volumeMounts:
        - name: app-config-volume
          mountPath: /config
      volumes:
        - name: app-config-volume
          configMap:
            name: java-producer-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-producer
  name: java-producer
  namespace: clients
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-producer
status:
  loadBalancer: {}